<?php

/**
 * @file
 * Contains leadgen_paragraphs.module..
 */

/**
 * Implements hook_preprocess_paragraph__banner().
 */
function leadgen_paragraphs_preprocess_paragraph__banner(&$variables) {
  /** @var \Drupal\leadgen_paragraphs\BannerParagraph $banner_renderer */
  $banner_renderer = \Drupal::service('leadgen_paragraphs.banner');
  $banner_renderer->render($variables);
}

/**
 * Implements hook_preprocess_paragraph__carousel().
 */
function leadgen_paragraphs_preprocess_paragraph__carousel(&$variables) {
  /** @var \Drupal\leadgen_paragraphs\CarouselParagraph $carousel_renderer */
  $carousel_renderer = \Drupal::service('leadgen_paragraphs.carousel');
  $carousel_renderer->render($variables);
}