<?php

/**
 * @file
 * Contains leadgen_paragraphs.module..
 */

use Drupal\image\Entity\ImageStyle;

/**
 * Implements hook_preprocess_paragraph__banner().
 */
function leadgen_paragraphs_preprocess_paragraph__banner(&$variables) {
  //@TODO Cleanup. Need to find a better way to do this...
  $paragraph = $variables['paragraph'];

  // If banner image and nested paragraphs are present.
  if (!$paragraph->field_image->isEmpty() && !$paragraph->field_paragraphs->isEmpty()) {
    // Get banner image.
    $banner_image_uri = $paragraph->field_image->entity->getFileUri();
    $banner_image = ImageStyle::load('banner')->buildUrl($banner_image_uri);
    // Add image as background.
    $variables['attributes']['style'][] = 'background-image: url("' . $banner_image . '");';
    $variables['attributes']['style'][] = 'background-size: cover;background-position: center center;';
    // Hide the normal <img> tag.
    hide($variables['content']['field_image']);
  }
  // Check if banner color is empty.
  if (!$paragraph->field_banner_color->isEmpty()) {
    $banner_color = $paragraph->field_banner_color->getValue();
    $banner_color = reset($banner_color);
    $variables['attributes']['style'][] = 'background: ' . $banner_color['color'] . ';';
  }

  // Check if text color is empty.
  if (!$paragraph->field_text_color->isEmpty()) {
    $text_color = $paragraph->field_text_color->getValue();
    $text_color = reset($text_color);
    $variables['attributes']['style'][] = 'color: ' . $text_color['color'] . ';';
  }

  if (!$paragraph->field_paragraphs->isEmpty()) {
    $paragraphs = $paragraph->field_paragraphs->referencedEntities();
    if (count($paragraphs) == 1) {
      $variables['attributes']['class'][] = 'paragraph--single-nested';
    }
    else {
      $variables['attributes']['class'][] = 'paragraph--multiple-nested';
    }
  }

}

/**
 * Implements hook_preprocess_paragraph__carousel().
 */
function leadgen_paragraphs_preprocess_paragraph__carousel(&$variables) {
  //@TODO Cleanup. Need to find a better way to do this...
  $slides = [];

  $paragraph = $variables['paragraph'];
  if (!$paragraph->field_paragraphs->isEmpty()) {
    $paragraphs = $paragraph->field_paragraphs->referencedEntities();
    foreach ($paragraphs as $slide_paragraph) {

      $item = [];
      if (!$slide_paragraph->field_title->isEmpty()) {
        $item['title'] = $slide_paragraph->field_title->value;
      }
      if (!$slide_paragraph->field_text->isEmpty()) {
        $item['description'] = [
          '#markup' => $slide_paragraph->field_text->value,
        ];
      }

      if (!$slide_paragraph->field_image->isEmpty()) {
        $image_uri = $slide_paragraph->field_image->entity->getFileUri();
        $image = ImageStyle::load('banner')->buildUrl($image_uri);
        // TODO Should use the theme_image or whatever it's called in D8.
        $item['image'] = [
          '#markup' => '<img src="' . $image . '" class="img-responsive center-block" />',
        ];
      }

      if (!empty($item)) {
        $slides[] = $item;
      }
    }

  }
  if(!empty($slides)) {
    $variables['content']['bootstrap_carousel'] = [
      '#theme' => 'bootstrap_carousel',
      '#slides' => $slides,
    ];
    hide($variables['content']['field_paragraphs']);
  }

}