<?php

/**
 * @file
 * Contains leadgen_widgets.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\image\Entity\ImageStyle;

/**
 * Implements hook_help().
 */
function leadgen_widgets_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the leadgen_widgets module.
    case 'help.page.leadgen_widgets':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function leadgen_widgets_theme() {
  $theme = [];

  return $theme;
}

/**
 * Implements hook_preprocess_paragraph().
 */
function leadgen_widgets_preprocess_paragraph(&$variables) {

}

/**
 * Implements hook_preprocess_paragraph__banner().
 */
function leadgen_widgets_preprocess_paragraph__banner(&$variables) {
  $paragraph = $variables['paragraph'];

  // If banner image and nested paragraphs are present.
  if (!$paragraph->field_banner_image->isEmpty() && !$paragraph->field_paragraphs->isEmpty()) {
    // Get banner image.
    $banner_image_uri = $paragraph->field_banner_image->entity->getFileUri();
    $banner_image = ImageStyle::load('banner')->buildUrl($banner_image_uri);
    // Add image as background.
    $variables['attributes']['style'][] = 'background-image: url("' . $banner_image . '");';
    $variables['attributes']['style'][] = 'background-size: cover;background-position: center center;';
    // Hide the normal <img> tag.
    hide($variables['content']['field_banner_image']);
  }
  // Check if banner color is empty.
  if (!$paragraph->field_banner_color->isEmpty()) {
    $banner_color = $paragraph->field_banner_color->getValue();
    $banner_color = reset($banner_color);
    $variables['attributes']['style'][] = 'background: ' . $banner_color['color'] . ';';
  }
}